# Базовый образ, содержащий Java
# FROM openjdk:27-ea-trixie
FROM eclipse-temurin:21-jre-alpine

# Директория приложения внутри контейнера
WORKDIR /app

# Копирование JAR-файла приложения в контейнер
COPY build/libs/newsservice-0.0.1-SNAPSHOT.jar app.jar

# Определение переменной среды
ENV APP_SERVER_PORT=8080
ENV DB_HOST=localhost
ENV DB_PORT=5436
ENV DB_NAME=news_db
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_SCHEMA=news_schema
ENV APP_ADMIN_USERNAME=admin
ENV APP_ADMIN_PASSWORD=admin

# Команда для запуска приложения
CMD ["java", "-jar", "app.jar"]