spring:
  application:
    name: newsservice
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
#      ddl-auto: validate
      ddl-auto: update
  liquibase:
    enabled: false
#    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: news_schema
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:news_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      schema: ${DB_SCHEMA:news_schema}
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000
  threads:
    virtual:
      enabled: true

server:
  port: ${APP_SERVER_PORT:8080}

app:
  security:
    adminUsername: ${APP_ADMIN_USERNAME:admin}
    adminPassword: ${APP_ADMIN_PASSWORD:admin}